language: node_js
node_js:
  - 12.13
services: docker
env:
  global:
  - PROJECT_NAME=logger
  - PROJECT_VERSION=1.0.0
  - DOCKER_USERNAME=bezpov
  - secure: HoGeiFzYQPxVPlj52gQ1iJAV0yZT8WOPxEhEkB6E5q9pgmp510LJG9xj6tbqaV8JEdh1gMyHH5UcG0WZ3g0ptsT1I8NjcD6yuVBNqCuPIXZ+APZzTk/umz7z+Zp265td9vq3SS1QA25GXYwMTIHvD1QNL60vcNJGJu5RJguDZW33iJ9Ixwy4QZill0KAiBopiC+n+q18UHwijB5X1AoOPj3jqsef70mF39DwDw/vQ1iFPmFB85D2+TdJjuV9ZYVh5zS5GijTWBi4M2M6sfAcrvjGeVuXdP4WkCjWrNLuj5w9eB/Dckicdo9sdQPwon5YfCBNoZ/AH4uUgqGlycChSXxHNqVdA/gLygZDghqiK1kUGs9efAwq3FkYjW9uf7LAK7yFDBn7sVXgygAx2DLKRqtLFS0F1uWHh10h9WivAMuoU//0BYQQLsWi1m2OyzeRwGH2569WQ3tvv6ajwf4b1ihaR7N0/Unh9r1FMzDegegM9wjgGQsNDNj+z8eD3U1dNm3lLUBnoq2VmNObAbOGc8QhAE5VHErVW3j6PUnKKZbE7AVR82PSzw4NZ9KksPfAEwdp2+S7ErcWtYEAUoL2989pmG9gSaunBkI0ljV+bqN1oLIJuhDzfO5VcyLWGObRsd5UCV2kuX6eSc1qIkTRqntkSkwQt+o9J+kghrOPaOw=
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
